name: TER

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.1

      - name: Install requirements
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: /home/runner/.composer/vendor/bin/phpunit --colors -c /home/runner/.composer/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.1

      - name: Install requirements
        run: composer global require --dev helhum/ter-client dev-master

      - name: Cleanup before we upload
        run: git reset --hard HEAD && git clean -fx

      - name: Create tag message
        run: echo `git tag -n10 -l $(git describe --abbrev=0 --tags) | sed 's/^[0-9.]*[ ]*//g'` >> TAG_MESSAGE

      - name: Build extension files
        run: composer extension-release

      - name: Publish to TER
        run: /home/runner/.composer/vendor/bin/ter-client upload t3telephone . -u "${{ secrets.TYPO3_ORG_USERNAME }}" -p "${{ secrets.TYPO3_ORG_PASSWORD }}" -m "$(cat TAG_MESSAGE)"
