name: Tests

on: push

jobs:
  # phpunit:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       php: [7.2, 7.3]
  #       TYPO3: [8.7, 9.5]
  #   name: PHP${{ matrix.php }} - TYPO3 ${{ matrix.TYPO3 }}
  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Set up PHP Version
  #       uses: shivammathur/setup-php@v1
  #       with:
  #         php-version: ${{ matrix.php }}
  #         extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
  #         coverage: none

  #     - name: Install dependencies
  #       run: composer require "typo3/cms-core:${{ matrix.TYPO3 }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update

      # - name: Execute tests
      #   run: ./vendor/bin/phpunit --colors -c ./vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit

  codingstyle:
    - uses: actions/checkout@v1

    - name: Set up PHP Version
      run: sudo update-alternatives --set php /usr/bin/php7.2

    - name: Install requirements
      run: composer global require --dev friendsofphp/php-cs-fixer

    - name: Execute style check
      run: /home/runner/.composer/vendor/bin/php-cs-fixer fix --dry-run --diff
