name: Tests

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.2

      - name: Install dependencies
        run: composer global require --dev "typo3/testing-framework:4.15" --no-interaction --no-update

      - name: Execute tests
        run: /home/runner/.composer/vendor/bin/phpunit --colors -c /home/runner/.composer/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit

  codingstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.2

      - name: Install requirements
        run: composer global require --dev friendsofphp/php-cs-fixer --no-interaction --no-update

      - name: Execute style check
        run: /home/runner/.composer/vendor/bin/php-cs-fixer fix --dry-run --diff
